# Generated by Django 3.2 on 2021-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211214_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_key_expores',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
