# Generated by Django 3.2 on 2021-12-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userprifile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrifile',
            new_name='UserProfile',
        ),
    ]
